package com.capstone.year.Readers;

import com.capstone.year.Models.YearModel;
import lombok.extern.slf4j.Slf4j;
import org.springframework.batch.core.configuration.annotation.StepScope;
import org.springframework.batch.item.NonTransientResourceException;
import org.springframework.batch.item.ParseException;
import org.springframework.batch.item.UnexpectedInputException;
import org.springframework.batch.item.file.FlatFileItemReader;
import org.springframework.batch.item.support.SynchronizedItemStreamReader;
import org.springframework.batch.item.support.builder.SynchronizedItemStreamReaderBuilder;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.context.annotation.Bean;
import org.springframework.core.io.FileSystemResource;
import org.springframework.stereotype.Component;

@Component
@Slf4j
public class YearReaderCSV {

    // FlatFileItemReader
    @StepScope
    @Bean("reader_Year")
    public SynchronizedItemStreamReader<YearModel> synchronizedItemStreamReader(
            @Value("#{jobParameters['file.input']}")
            String source_input
    ) throws UnexpectedInputException,
            NonTransientResourceException, ParseException {

        FlatFileItemReader<YearModel> itemReader = new FlatFileItemReader<>();
        itemReader.setResource(new FileSystemResource(source_input));
        itemReader.setLinesToSkip(1);
        itemReader.setLineMapper((line, lineNumber) -> {
            String[] fields = line.split(",");
            YearModel transaction = new YearModel();

            transaction.setUserID(Long.parseLong(fields[0]));
            transaction.setCardID(Long.parseLong(fields[1]));
            transaction.setTransactionYear(fields[2]);
            transaction.setTransactionMonth(fields[3]);
            transaction.setTransactionDay(fields[4]);
            transaction.setTransactionTime(fields[5]);
            transaction.setTransactionAmount(fields[6]);
            transaction.setTransactionType(fields[7]);
            transaction.setMerchantID(Long.parseLong(fields[8]));
            transaction.setTransactionCity(fields[9]);
            transaction.setTransactionState(fields[10]);
            transaction.setTransactionZip(fields[11]);
            transaction.setMerchantCatCode(Long.parseLong(fields[12]));

            // If error messages present, take all errors as a string and iterate through all
            // extra fields that are generated (one per error message present). The last field
            // should be the Fraud Check field
            if (fields[13].contains("\"")) {

                String errorList = ""; // create empty string
                // Iterate through all error message fields generated by regex
                for (int i = 13; i < fields.length - 1; i++) {

                    // Get first error message excluding the first double quote "
                    if (i == 13) {
                        String temp = fields[i].substring(1);
                        errorList = errorList + temp + ","; // add error to string
                    }

                    // If last field is ", end of error messages has been reached
                    else if (fields[i].equals("\"")) {
                        // do nothing. Error message string will have comma at the end of it
                    }
                    // End of error messages hasn't been reached yet
                    else {
                        errorList = errorList + fields[i] + ","; // add error to string
                    }

                }
                transaction.setTransactionErrorCheck(errorList);
                transaction.setTransactionFraudCheck(fields[fields.length - 1]);
            }
            else {
                // No error messages present in transaction
                transaction.setTransactionErrorCheck(fields[13]);
                transaction.setTransactionFraudCheck(fields[14]);
            }

            return transaction;
        });

        // Make FlatFileItemReader thread-safe
        return new SynchronizedItemStreamReaderBuilder<YearModel>()
                .delegate(itemReader)
                .build();
    }
}
